# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1536, 864)
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".sec1").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".login_btn").click()
    time.sleep(1)

    self.driver.find_element(By.NAME, "name").click()
    time.sleep(0.5)
    self.driver.find_element(By.NAME, "name").send_keys("queen")
    time.sleep(1)

    self.driver.find_element(By.NAME, "email").click()
    time.sleep(0.5)
    self.driver.find_element(By.NAME, "email").send_keys("queen123@gmail.com")
    time.sleep(1)

    self.driver.find_element(By.NAME, "password").click()
    time.sleep(0.5)
    self.driver.find_element(By.NAME, "password").send_keys("123456789")
    time.sleep(1)

    self.driver.find_element(By.NAME, "submit").click()
    time.sleep(2)

    self.driver.find_element(By.CSS_SELECTOR, ".sec1").click()
    time.sleep(1)
