# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOrder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_order(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1536, 864)
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".sec1").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".login_btn").click()
    time.sleep(1)

    self.driver.find_element(By.LINK_TEXT, "Already have an account?").click()
    time.sleep(1)

    self.driver.find_element(By.NAME, "email").click()
    time.sleep(0.5)
    self.driver.find_element(By.NAME, "email").send_keys("sylvia22@gmail.com")
    time.sleep(1)

    self.driver.find_element(By.NAME, "password").click()
    time.sleep(0.5)
    self.driver.find_element(By.NAME, "password").send_keys("1234567890")
    time.sleep(1)

    self.driver.find_element(By.NAME, "submit").click()
    time.sleep(2)

    self.driver.find_element(By.LINK_TEXT, "Menu").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".OurMenu").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, "#appetizers .menu-item:nth-child(1) > .add-to-cart-btn").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".checkout-btn").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, ".table-option:nth-child(8)").click()
    time.sleep(1)

    self.driver.find_element(By.ID, "confirmTableBtn").click()
    time.sleep(1)

    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    time.sleep(1)
