# Generated by Selenium IDE
import pytest #pytest=selenium module to create automation
import time
import json
from selenium import webdriver #webdriver=module which help to access the website elements
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome() #self is the structure for this cls,helps to initialize value in constructor
    self.vars = {}
  

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1536, 864)
    self.driver.find_element(By.CSS_SELECTOR, ".login_btn").click()
    time.sleep(1) #slow down next execution by 1 sec
    # print("button found")
    self.driver.find_element(By.LINK_TEXT, "Already have an account?").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").send_keys("sylvia22@gmail.com")
    time.sleep(1)
    # print("email entered")
    self.driver.find_element(By.NAME, "password").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "password").send_keys("1234567890")
    time.sleep(1)
    # print("password entered")
    self.driver.find_element(By.NAME, "submit").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".sec1").click()
    time.sleep(1)
    
  
